security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            security: true  # If you are using HTTP Basic or HTTP Digest authentication
            provider: app_user_provider
            entry_point: form_login
            form_login:
                login_path: security_login
                check_path: security_login
                enable_csrf: true
            logout:
                path: security_logout
                target: /
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 1 week in seconds

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    # Conrole d'accès aux différentes routes de l'application    
    access_control:
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/utilisateurs, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/fiches, roles: ROLE_USER }
        - { path: ^/entreprises, roles: ROLE_USER }
        - { path: ^/recherche, roles: ROLE_USER }
        - { path: ^/listing, roles: ROLE_USER }
        - { path: ^/historique, roles: ROLE_ADMIN }
        - { path: ^/notifications, roles: ROLE_USER }
        - { path: ^/entreprises/\d+/supprimer, roles: ROLE_ADMIN }
        - { path: ^/entreprises/export, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
