framework:
    workflows:
        prospection:
            type: 'workflow'  # Modification de 'state_machine' à 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\FicheEntreprise
            initial_marking: nouveau
            places:
                - nouveau
                - en_cours
                - contacté
                - rendez_vous
                - conclu
                - rejeté
            transitions:
                demarrer:
                    from: nouveau
                    to: en_cours
                contacter:
                    from: en_cours
                    to: contacté
                planifier:
                    from: contacté
                    to: rendez_vous
                conclure:
                    from: rendez_vous
                    to: conclu
                rejeter:
                    from: [nouveau, en_cours, contacté, rendez_vous]
                    to: rejeté
