framework:
    workflows:
        prospection:
            type: state_machine
            supports:
                - App\Entity\FicheEntreprise
            initial_marking: nouveau
            marking_store:
                type: method
                property: statut
            places:
                - nouveau
                - en_cours
                - validé
                - archivé
            transitions:
                demarrer:
                    from: nouveau
                    to: en_cours
                valider:
                    from: en_cours
                    to: validé
                archiver:
                    from: validé
                    to: archivé
