controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_controllers:
    resource:
        path: ../src/Controller/Api/
        namespace: App\Controller\Api
    prefix: /api
    type: attribute

# Définir un alias de route pour éviter les erreurs de redirection
dashboard:
    path: /dashboard
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: dashboard_index
        permanent: true

# Ajout d'un alias pour la route app_login
app_login:
    path: /login
    controller: App\Controller\SecurityController::login
    methods: ['GET', 'POST']

# Route d'authentification JWT directe
api_login_check:
    path: /api/login_check
    methods: ['POST']

# Route d'authentification alternative
api_token_authenticate:
    path: /token/authenticate
    controller: App\Controller\SecurityController::apiTokenAuthenticate
    methods: ['POST']

# Endpoint de test d'authentification
api_auth_test:
    path: /auth-test
    controller: App\Controller\Api\SecurityController::testAuthentication
    methods: ['GET']

api_auth_status:
    path: /auth-status
    controller: App\Controller\Api\SecurityController::getUserStatus
    methods: ['GET']

# Route d'authentification JWT clé en main en POST
api_login:
    path: /login
    methods: ['POST']
    defaults:
        _controller: 'App\Controller\LoginAliasController::login'
